'use client';
import { useEffect, useMemo, useState } from 'react';
import { Bar, BarChart, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
type SetRecord={year:number;theme:string;pieces:number;uniqueRatio:number;colors:number;minifigs:number;specializedShare:number}; type Dataset={sets:SetRecord[];methodology:Record<string,string>};
const avg=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:0; const med=(v:number[])=>{const s=[...v].sort((a,b)=>a-b),m=Math.floor(s.length/2);return s.length?s.length%2?s[m]:(s[m-1]+s[m])/2:0}; const p95=(v:number[])=>[...v].sort((a,b)=>a-b)[Math.floor(v.length*.95)]||1; const num=(v:number)=>new Intl.NumberFormat('en-US',{maximumFractionDigits:0}).format(v); const tip={background:'#f7f5f1',border:'1px solid #17223633',borderRadius:0};
function Card({title,note,children}:{title:string;note:string;children:React.ReactElement}){return <div className="mt-8 border border-[#172236]/15 bg-[#f7f5f1] p-5 sm:p-7"><h3 className="text-lg font-medium">{title}</h3><p className="mt-1 text-sm text-[#172236]/60">{note}</p><div className="mt-5 h-[300px]"><ResponsiveContainer width="100%" height="100%">{children}</ResponsiveContainer></div></div>}
function Metric({label,value,note}:{label:string;value:string;note:string}){return <article className="bg-[#f7f5f1] p-5"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-[#172236]/55">{label}</p><p className="mt-3 text-3xl font-medium tracking-tight">{value}</p><p className="mt-1 text-xs text-[#172236]/60">{note}</p></article>}
function Score({weight,name,value}:{weight:string;name:string;value:string}){return <div className="border-t border-[#172236]/15 pt-3"><p className="text-sm font-medium"><span className="mr-2 text-[#ad3345]">{weight}</span>{name}</p><p className="mt-1 font-mono text-[11px] text-[#172236]/55">{value}</p></div>}
export default function Home(){
 const [data,setData]=useState<Dataset|null>(null),[range,setRange]=useState<[number,number]>([1949,2027]),[chosen,setChosen]=useState<string[]>([]);
 useEffect(()=>{fetch('/data/lego-summary.json').then(r=>r.json()).then(setData)},[]);
 const records=useMemo(()=>data?.sets.filter(s=>s.year>=range[0]&&s.year<=range[1]&&(!chosen.length||chosen.includes(s.theme)))??[],[data,range,chosen]);
 const yearly=useMemo(()=>{const map=new Map<number,SetRecord[]>();records.forEach(s=>map.set(s.year,[...(map.get(s.year)??[]),s]));return [...map].map(([year,r])=>({year,pieces:Math.round(med(r.map(s=>s.pieces))),unique:+(avg(r.map(s=>s.uniqueRatio))*100).toFixed(1),colors:+avg(r.map(s=>s.colors)).toFixed(1),minifigs:+avg(r.map(s=>s.minifigs)).toFixed(1),specialized:+(avg(r.map(s=>s.specializedShare))*100).toFixed(1)})).sort((a,b)=>a.year-b.year)},[records]);
 if(!data)return <main className="grid min-h-screen place-items-center bg-[#eeece8] text-[#172236]">Reading the brick archive…</main>;
 const ref={pieces:p95(data.sets.map(s=>s.pieces)),colors:p95(data.sets.map(s=>s.colors)),figs:p95(data.sets.map(s=>s.minifigs))},pieces=records.map(s=>s.pieces);
 const scores=records.map(s=>100*(.4*Math.min(1,Math.log1p(s.pieces)/Math.log1p(ref.pieces))+.25*s.uniqueRatio+.2*Math.min(1,s.colors/ref.colors)+.15*Math.min(1,s.minifigs/ref.figs)));
 const bins=[[0,49],[50,99],[100,249],[250,499],[500,999],[1000,2499],[2500,Infinity]].map(([min,max])=>({label:max===Infinity?'2,500+':num(min)+'–'+num(max),sets:records.filter(s=>s.pieces>=min&&s.pieces<=max).length}));
 const toggle=(t:string)=>setChosen(v=>v.includes(t)?v.filter(x=>x!==t):[...v,t]);
 return <main className="min-h-screen bg-[#eeece8] text-[#172236]"><header className="border-b border-[#172236]/15 bg-[#f7f5f1] px-5 py-5 sm:px-10"><div className="mx-auto flex max-w-7xl items-end justify-between gap-6"><div><p className="mb-2 text-[10px] font-bold uppercase tracking-[.22em] text-[#ad3345]">A data study · 1949–2027</p><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">LEGO Inflation <span className="font-normal text-[#172236]/55">— Without Prices</span></h1></div><p className="hidden max-w-xs text-right text-sm leading-5 text-[#172236]/65 lg:block">How much structural and creative complexity does a LEGO set deliver?</p></div></header><section className="mx-auto max-w-7xl px-5 py-8 sm:px-10 sm:py-12">
 <div className="mb-8 grid gap-6 border-b border-[#172236]/15 pb-8 lg:grid-cols-[1fr_1.3fr]"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#172236]/55">The big picture</p><h2 className="mt-2 max-w-xl text-3xl leading-tight tracking-tight sm:text-4xl">More than part counts: a changing toolkit for making things.</h2></div><div className="space-y-4 lg:pt-1"><div className="flex items-center justify-between text-xs font-bold uppercase tracking-[.12em]"><span>Release years</span><span className="text-[#ad3345]">{range[0]} — {range[1]}</span></div><div className="grid grid-cols-2 gap-3"><label className="text-sm">From<input className="mt-1 block w-full border border-[#172236]/20 bg-transparent px-3 py-2" type="number" min="1949" max={range[1]} value={range[0]} onChange={e=>setRange([Math.min(+e.target.value,range[1]),range[1]])}/></label><label className="text-sm">To<input className="mt-1 block w-full border border-[#172236]/20 bg-transparent px-3 py-2" type="number" min={range[0]} max="2027" value={range[1]} onChange={e=>setRange([range[0],Math.max(+e.target.value,range[0])])}/></label></div></div></div>
 <div className="mb-8 flex flex-wrap gap-2">{['City','Space','Castle','Technic','Star Wars','Friends'].map(t=><button key={t} onClick={()=>toggle(t)} className={'border px-3 py-1.5 text-sm '+(chosen.includes(t)?'border-[#ad3345] bg-[#ad3345] text-white':'border-[#172236]/20 bg-[#f7f5f1]')}>{t}</button>)}{chosen.length>0&&<button onClick={()=>setChosen([])} className="px-2 text-sm underline underline-offset-4">Clear filters</button>}</div>
 <div className="grid gap-px overflow-hidden border border-[#172236]/15 bg-[#172236]/15 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Sets with inventories" value={num(records.length)} note="Canonical inventory version"/><Metric label="Median pieces / set" value={num(med(pieces))} note={'Average '+num(avg(pieces))}/><Metric label="Unique-part ratio" value={(avg(records.map(s=>s.uniqueRatio))*100).toFixed(1)+'%'} note="Distinct part numbers / quantity"/><Metric label="Colors & figures" value={avg(records.map(s=>s.colors)).toFixed(1)+' / '+avg(records.map(s=>s.minifigs)).toFixed(1)} note="Average colors / minifigures per set"/></div>
 <Card title="Complexity trajectories" note="Median pieces; average diversity, color count, and minifigure density. Hover to inspect a year."><LineChart data={yearly}><XAxis dataKey="year" tickLine={false} axisLine={false} minTickGap={28}/><YAxis yAxisId="pieces" tickLine={false} axisLine={false} width={42}/><YAxis yAxisId="other" orientation="right" tickLine={false} axisLine={false} width={38}/><Tooltip contentStyle={tip}/><Line yAxisId="pieces" type="monotone" dataKey="pieces" name="Median pieces" stroke="#ad3345" strokeWidth={2.5} dot={false}/><Line yAxisId="other" type="monotone" dataKey="unique" name="Unique-part ratio (%)" stroke="#3a6595" strokeWidth={2} dot={false}/><Line yAxisId="other" type="monotone" dataKey="colors" name="Colors / set" stroke="#5e718c" strokeWidth={2} dot={false}/><Line yAxisId="other" type="monotone" dataKey="minifigs" name="Minifigures / set" stroke="#172236" strokeWidth={1.5} strokeDasharray="4 4" dot={false}/></LineChart></Card>
 <section className="mt-14 border-t border-[#172236]/15 pt-10"><div className="grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#ad3345]">What “inflation” means here</p><h2 className="mt-3 text-3xl leading-tight tracking-tight">Creative Density</h2><p className="mt-4 max-w-md text-sm leading-6 text-[#172236]/70">A transparent, non-price score for the mix of structural scale, distinct elements, color variety, and characters a set offers.</p><div className="mt-6 border-l-2 border-[#ad3345] pl-4"><p className="text-[11px] font-bold uppercase tracking-[.12em] text-[#172236]/55">Median score in selection</p><p className="mt-1 text-5xl font-medium tracking-tight">{med(scores).toFixed(0)}<span className="text-xl text-[#172236]/50">/100</span></p></div></div><div className="border border-[#172236]/15 bg-[#f7f5f1] p-5 sm:p-7"><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#172236]/55">Formula · capped at full-dataset 95th percentile</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Score weight="40%" name="Structural scale" value={'log pieces / log '+num(ref.pieces)+' pieces'}/><Score weight="25%" name="Part diversity" value="unique-part ratio"/><Score weight="20%" name="Color variety" value={'distinct colors / '+num(ref.colors)}/><Score weight="15%" name="Character density" value={'minifigures / '+num(ref.figs)}/></div><p className="mt-5 text-xs leading-5 text-[#172236]/55">The cap prevents extreme collector-scale sets from overpowering the result. It is a comparative index, not a quality rating.</p></div></div></section>
 <section className="mt-14 border-t border-[#172236]/15 pt-10"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#ad3345]">Structural complexity</p><h2 className="mt-2 text-3xl tracking-tight">Averages can hide the range of LEGO sets.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-[#172236]/65">Piece count captures scale. The comparison below separates variety of designs from the types of physical pieces selected for a build.</p><div><Card title="Piece-count distribution" note="Number of sets in each size band."><BarChart data={bins}><XAxis dataKey="label" tickLine={false} axisLine={false}/><YAxis tickLine={false} axisLine={false}/><Tooltip cursor={{fill:'#1722360b'}} contentStyle={tip}/><Bar dataKey="sets" name="Sets" fill="#3a6595"/></BarChart></Card><Card title="Part variety & specialized elements" note="Both measures are percentages. Blue: distinct part designs per 100 physical pieces (less repetition). Red: share of actual pieces beyond basic bricks, plates, and tiles — such as wheels, hinges, figures, or Technic connectors."><LineChart data={yearly}><XAxis dataKey="year" tickLine={false} axisLine={false} minTickGap={28}/><YAxis tickLine={false} axisLine={false} unit="%" domain={[0,100]}/><Tooltip contentStyle={tip}/><Line type="monotone" dataKey="unique" name="Part variety" stroke="#3a6595" strokeWidth={2.5} dot={false}/><Line type="monotone" dataKey="specialized" name="Specialized physical pieces" stroke="#ad3345" strokeWidth={2.5} dot={false}/></LineChart></Card></div></section>
 <p className="mt-10 max-w-3xl text-xs leading-5 text-[#172236]/55">Current method: {data.methodology.canonicalInventory} Basic parts are {data.methodology.basicParts} {data.methodology.reliableYears}</p></section></main>
}
